name: RecipeWise
description: An application that will make life easier for those who want to cook

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.5.3"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  image_picker: ^1.1.2  # Adicione o image_picker corretamente
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.2
  camera: ^0.11.0+2
  carousel_slider: ^5.0.0
  stylish_bottom_bar: ^1.1.0
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
